"""Structured schemas and models for CodePilot multi-agent system."""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class AgentRole(str, Enum):
    """The specialized roles in the system."""
    CODE_ANALYSIS = "code_analysis"
    DEBUGGING = "debugging"
    TESTING = "testing"
    ORCHESTRATOR = "orchestrator"


class TaskStatus(str, Enum):
    """Status lifecycle of a task or step."""
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILURE = "failure"
    NEEDS_RETRY = "needs_retry"
    SKIPPED = "skipped"


class InputMode(str, Enum):
    """User input modes supported by CodePilot."""
    PASTE_CODE = "paste_code"
    GITHUB_REPO = "github_repo"
    GENERAL_QUERY = "general_query"


class ToolCall(BaseModel):
    """Representation of an invoked tool call."""
    call_id: str = Field(default="", description="Unique identifier for the tool call")
    tool_name: str = Field(description="Name of the MCP tool called")
    arguments: Dict[str, Any] = Field(default_factory=dict, description="Arguments passed to the tool")


class ToolResult(BaseModel):
    """Structured result returned by an MCP tool."""
    tool_name: str
    is_error: bool = False
    output: str = ""
    structured_data: Optional[Dict[str, Any]] = None
    execution_time_ms: float = 0.0


class ValidationResult(BaseModel):
    """Structured test suite and validation results."""
    passed: bool = Field(default=False, description="Whether tests passed cleanly")
    test_framework: str = Field(default="unknown", description="e.g. pytest, unittest, jest")
    total_tests: int = 0
    passed_tests: int = 0
    failed_tests: int = 0
    error_tests: int = 0
    failure_category: Optional[str] = Field(
        default=None,
        description="One of: 'fix_failure', 'unrelated_failure', 'environment_failure', 'syntax_error', 'none'"
    )
    test_command: str = ""
    raw_output: str = ""
    details: List[str] = Field(default_factory=list)


class PlanStep(BaseModel):
    """A single step inside an execution plan."""
    step_id: int = Field(description="Sequential step index (1-based)")
    agent: AgentRole = Field(description="Selected specialized agent for this step")
    objective: str = Field(description="Clear actionable objective for the agent")
    context: str = Field(default="", description="Contextual info and inputs passed from prior steps")
    expected_output: str = Field(description="Expected structured deliverable from this step")
    dependencies: List[int] = Field(default_factory=list, description="Step IDs that must finish first")
    allowed_tools: List[str] = Field(default_factory=list, description="Explicit tools permitted for this step")


class ExecutionPlan(BaseModel):
    """The structured multi-agent plan generated by the LLM Planner."""
    user_intent: str = Field(description="Analysis of what the user is asking to achieve")
    steps: List[PlanStep] = Field(description="Ordered list of agent steps to execute")
    estimated_complexity: str = Field(default="medium", description="low, medium, or high")
    rationale: str = Field(description="Reasoning behind why these agents and steps were selected")


class AgentTask(BaseModel):
    """Specific task payload delivered to a worker agent."""
    task_id: str
    role: AgentRole
    objective: str
    workspace_path: str
    context: Dict[str, Any] = Field(default_factory=dict)
    retrieved_code_chunks: List[Dict[str, Any]] = Field(default_factory=list)
    allowed_tools: List[str] = Field(default_factory=list)
    retry_attempt: int = 0
    feedback: Optional[str] = None


class AgentResult(BaseModel):
    """Structured outcome produced by a worker agent."""
    status: TaskStatus = TaskStatus.SUCCESS
    agent: AgentRole
    summary: str = Field(description="Concise description of work done")
    evidence: str = Field(description="Direct tool output, diffs, or logs proving what happened")
    files_inspected: List[str] = Field(default_factory=list)
    changes_made: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of dicts: {'file_path': str, 'summary': str, 'diff': str}"
    )
    tests_executed: List[str] = Field(default_factory=list)
    validation: Optional[ValidationResult] = None
    errors: List[str] = Field(default_factory=list)
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    recommended_next_action: str = Field(default="")
    tool_calls_made: List[ToolCall] = Field(default_factory=list)


class EvaluationCriteria(BaseModel):
    """Breakdown of quality criteria in the final evaluation stage."""
    relevant_code_inspected: bool = False
    proposed_modification_addresses_problem: bool = False
    tests_executed: bool = False
    tests_passed: bool = False
    no_unresolved_errors: bool = False
    claims_supported_by_evidence: bool = False


class EvaluationResult(BaseModel):
    """Outcome of the final evaluation stage before showing result to user."""
    is_objective_completed: bool = False
    quality_score: float = Field(default=0.0, ge=0.0, le=1.0)
    criteria: EvaluationCriteria = Field(default_factory=EvaluationCriteria)
    reasoning: str = ""
    requires_retry: bool = False
    retry_target_agent: Optional[AgentRole] = None
    retry_guidance: Optional[str] = None


class FinalResult(BaseModel):
    """Final synthesis presented to the user."""
    success: bool
    summary: str
    solution_code: Optional[str] = None
    solution_language: Optional[str] = None
    files_modified: List[Dict[str, Any]] = Field(default_factory=list)
    test_evidence: Optional[ValidationResult] = None
    execution_timeline: List[Dict[str, Any]] = Field(default_factory=list)
    evaluation: Optional[EvaluationResult] = None
    raw_error: Optional[str] = None


class UserRequest(BaseModel):
    """Payload received from the chatbot frontend."""
    message: str
    input_mode: InputMode = InputMode.GENERAL_QUERY
    code_snippet: Optional[str] = None
    code_language: Optional[str] = "python"
    error_message: Optional[str] = None
    github_url: Optional[str] = None
    session_id: Optional[str] = None


class WorkflowProgressEvent(BaseModel):
    """Event streamed to the frontend for real-time progress updates."""
    step: str
    status: str
    message: str
    agent: Optional[str] = None
    tool_call: Optional[Dict[str, Any]] = None
    details: Optional[Dict[str, Any]] = None
